export const ROUTES = {
  loading: 'LOADING',
  home: 'HOME',
  oops: 'OOPS',
  activePlot: 'ACTIVE_PLOT',
  plotList: 'PLOT_LIST',
  worldConstructor: 'WORLD_CONSTRUCTOR',
  laws: 'LAWS',
  waterholes: 'WATERHOLES',
  aboutWorld: 'ABOUT_WORLD',
  activeCalls: 'ACTIVE_CALLS',
  activeCall: 'ACTIVE_CALL',
  aboutEdge: 'ABOUT_EDGE',
  rewards: 'REWARDS',
  activeChallenges: 'ACTIVE_CHALLENGES',
  passedChallenges: 'PASSED_CHALLENGES',
  failedChallenges: 'FAILED_CHALLENGES',
  characters: 'CHARACTERS',
  charactersConstructor: 'CHARACTERS_CONSTRUCTOR',
  taskConstructor: 'TASK_CONSTRUCTOR',
  tasks: 'TASKS',
};
