export const ROUTES = {
  loading: 'LOADING',
  home: 'HOME',
  oops: 'OOPS',
  plotList: 'PLOT_LIST',
  worldConstructor: 'WORLD_CONSTRUCTOR',
  laws: 'LAWS',
  waterholes: 'WATERHOLES',
  aboutWorld: 'ABOUT_WORLD',
  activeCalls: 'ACTIVE_CALLS',
  aboutEdge: 'ABOUT_EDGE',
  rewards: 'REWARDS',
  activeChallenges: 'ACTIVE_CHALLENGES',
  passedChallenges: 'PASSED_CHALLENGES',
  failedChallenges: 'FAILED_CHALLENGES',
  characters: 'CHARACTERS' as const,
};
